// <auto-generated />
using System;
using FidenzApp.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FidenzApp.Infranstructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918123222_seeded two users")]
    partial class seededtwousers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FidenzApp.Domain.Entities.Customers", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eyeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.ToTable("Customers_Tb");
                });

            modelBuilder.Entity("FidenzApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users_Tb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "AQAAAAIAAYagAAAAEEdN9Y0LV515WwrU/pKNDUenHM35c4l6l9JzF7Q620qqlB7KdvG5oDtILQnO2B7LLg==",
                            Role = "Admin",
                            Username = "FidenzAdmin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            PasswordHash = "AQAAAAIAAYagAAAAEH9zxTSV3LJh9ptiWUjvNUJR1ZtqdCAWxXP52j9qpMaWyG6MB15ztNqaD0uRRW3JNQ==",
                            Role = "User",
                            Username = "FidenzUser"
                        });
                });

            modelBuilder.Entity("FidenzApp.Domain.Entities.Customers", b =>
                {
                    b.OwnsOne("FidenzApp.Domain.Entities.Address", "address", b1 =>
                        {
                            b1.Property<string>("Customers_id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("city")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("number")
                                .HasColumnType("int");

                            b1.Property<string>("state")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("zipcode")
                                .HasColumnType("int");

                            b1.HasKey("Customers_id");

                            b1.ToTable("Customers_Tb");

                            b1.WithOwner()
                                .HasForeignKey("Customers_id");
                        });

                    b.Navigation("address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
